In [6]:
import pandas as pd
df = pd.read_csv("311_Service_Requests_2020.csv")
df.head(5)

C:\Users\17832\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (20,31,32) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,45285347,01/01/2020 12:00:00 AM,01/10/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,3 or More,Restaurant/Bar/Deli/Bakery,11229.0,3442 NOSTRAND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.600129,-73.941843,"(40.6001292057807, -73.94184291675883)"
1,45285651,01/01/2020 12:00:00 AM,01/02/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Restaurant/Bar/Deli/Bakery,10458.0,2701 DECATUR AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.864866,-73.888783,"(40.86486556770799, -73.88878325729915)"
2,45285821,01/01/2020 12:00:00 AM,01/02/2020 09:50:09 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Other (Explain Below),11203.0,5707 CHURCH AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.652536,-73.923540,"(40.65253575905768, -73.92353994017134)"
3,45287907,01/01/2020 12:00:00 AM,01/02/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,3 or More,Restaurant/Bar/Deli/Bakery,11214.0,1602 SHORE PARKWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.595653,-74.000173,"(40.59565343138651, -74.00017283917487)"
4,45288240,01/01/2020 12:00:00 AM,01/02/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Restaurant/Bar/Deli/Bakery,11385.0,1717 CORNELIA STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.700366,-73.905438,"(40.700366489799876, -73.90543829006366)"

No missing data in 'Unique Key' and 'Complaint Type' column

In [15]:
df[['Unique Key','Complaint Type']].isnull().values.any()

False

Confirm that the data only include calls in 2020

In [9]:
df['year'] = df['Created Date'].str[6:10]
df[df['year']!='2020']

Empty DataFrame
Columns: [Unique Key, Created Date, Closed Date, Agency, Agency Name, Complaint Type, Descriptor, Location Type, Incident Zip, Incident Address, Street Name, Cross Street 1, Cross Street 2, Intersection Street 1, Intersection Street 2, Address Type, City, Landmark, Facility Type, Status, Due Date, Resolution Description, Resolution Action Updated Date, Community Board, BBL, Borough, X Coordinate (State Plane), Y Coordinate (State Plane), Open Data Channel Type, Park Facility Name, Park Borough, Vehicle Type, Taxi Company Borough, Taxi Pick Up Location, Bridge Highway Name, Bridge Highway Direction, Road Ramp, Bridge Highway Segment, Latitude, Longitude, Location, year]
Index: []

[0 rows x 42 columns]

Filter the original df to only include illegal parking calls in 2020

In [10]:
df_illegal_park = df[ (df['Complaint Type'] == 'Illegal Parking')]
df_illegal_park.head(5)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location,year
18,45279489,01/01/2020 12:04:47 AM,01/01/2020 04:22:13 AM,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11223.0,1906 WEST 13 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,40.599967,-73.984872,"(40.599967258222144, -73.98487199397107)",2020
32,45280049,01/01/2020 12:09:59 AM,01/01/2020 06:40:57 AM,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11217.0,484 STATE STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,40.686293,-73.981160,"(40.68629293677919, -73.98116016161326)",2020
37,45281799,01/01/2020 12:10:56 AM,01/03/2020 03:28:49 AM,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,10466.0,4327 WILDER AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,40.897928,-73.843708,"(40.89792803897644, -73.8437083217415)",2020
46,45281904,01/01/2020 12:12:37 AM,01/01/2020 01:46:46 PM,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,NaN,10470.0,221 EAST 237 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,40.898702,-73.869856,"(40.8987015413494, -73.86985551710447)",2020
56,45278396,01/01/2020 12:15:55 AM,01/01/2020 11:06:07 AM,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11378.0,60-17 59 ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,40.718183,-73.905658,"(40.718182937426654, -73.90565831800562)",2020

In [ ]:
total_incidents = df['Unique Key'].count()